env_name          : 'sawyer_peg_insertion-v1'
sim_env_name      : 'sawyer_peg_insertion-v0'
n_episodes        : 30
max_ep_length     : 75
seed              : 999 #testing: 0, tuning: 123
render            : True
job_mode          : 'sweep'
exp_notes         : '7-DOF Sawyer arm inserting peg in a hole at different locations'

random_shooting:
  horizon           : 16
  init_cov          : 0.15
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 10
  particles_per_cpu : 4
  sample_mode       : 'mean'
  base_action       : 'null'


# mppi:
#   horizon           : 16
#   init_cov          : 0.25
#   filter_coeffs     : [0.25, 0.8, 0.0]
#   gamma             : 1.0
#   n_iters           : 1
#   step_size         : 1.0
#   lam               : 0.1
#   alpha             : 1
#   num_cpu           : 10
#   particles_per_cpu : 6
#   sample_mode       : 'mean'
#   base_action       : 'null'
#   time_based_weights: False

# mppi:
#   horizon           : 32
#   init_cov          : 0.1
#   filter_coeffs     : [0.25, 0.8, 0.0]
#   gamma             : 0.99
#   n_iters           : 1
#   step_size         : 0.9
#   lam               : 0.005
#   alpha             : 1
#   num_cpu           : 10
#   particles_per_cpu : 12
#   sample_mode       : 'mean'
#   base_action       : 'null'
#   time_based_weights: False

mppi:
  horizon           : 20 #16
  init_cov          : 0.25 #0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 0.99 #1.0
  n_iters           : 1
  step_size         : 0.9 #1.0
  lam               : 0.1
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : 10 #4
  sample_mode       : 'mean'
  base_action       : 'null'
  time_based_weights: False



mppiq:
  horizon           : 16
  init_cov          : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  beta              : 0.1
  td_lam            : 1.0
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : 4
  sample_mode       : 'mean'
  base_action       : 'null'


cem:
  horizon           : 16
  init_cov          : 0.15
  cov_type          : 'full'
  beta              : 0.45
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.1
  num_cpu           : 10
  particles_per_cpu : 4
  sample_mode       : 'mean'
  base_action       : 'null'


dmd:
  horizon           : 16
  init_cov          : 0.45
  update_cov        : True
  cov_type          : 'full'
  beta              : 0.85
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 0.7
  lam               : 0.1
  num_cpu           : 10
  particles_per_cpu : 4
  sample_mode       : 'mean'
  base_action       : 'null'


pfmpc:
  horizon           : 16
  cov_shift         : 0.55
  cov_resample      : 1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  lam               : 0.2
  num_cpu           : 10
  particles_per_cpu : 4
  sample_mode       : 'mean'
  base_action       : 'null'
