env_name          : 'sawyer_peg_insertion-v0'
n_episodes        : 1
max_ep_length     : 75
seed              : 123 #testing: 0, tuning: 123
render            : True
job_mode          : 'sweep'
randomize_dyn     : False
exp_notes         : 'Swingup of cartpole'

actor_params:
  actor_type   : 'linear_gaussian'
  min_log_std  : -0.1
  init_log_std : 0.0

critic_params:
  critic_type       : None


# reinforce:
#   horizon           : 32
#   gamma             : 0.99
#   n_iters           : 5
#   lr                : 0.01
#   num_cpu           : 10
#   particles_per_cpu : 6
#   kl_delta          : 100
#   max_linesearch_iters: 100

reinforce:
  horizon           : 16
  gamma             : 1.0
  n_iters           : 1
  lr                : 0.2
  # beta              : 0.5
  filter_coeffs     : [1.0, 0.0, 0.0]
  num_cpu           : 10
  particles_per_cpu : 4
  delta_kl          : 1.0
  delta_reg         : 0.0001
  max_linesearch_iters: 100

  #TODO - Add covariance growing and different covariance types
