env_name          : 'sawyer_peg_insertion-v0'
n_episodes        : 20
max_ep_length     : 75
seed              : 123 #testing: 0, tuning: 123
base_action       : 'null'
render            : True
job_mode          : 'sweep'
exp_notes         : '7-DOF Sawyer arm inserting peg in a hole at different locations'

random_shooting:
  horizon           : 16
  init_cov          : 0.15
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 10
  particles_per_cpu : 4
  base_action       : 'null'

mppi:
  horizon           : 16
  init_cov          : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.1
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : 4
  base_action       : 'null'
  time_based_weights: False


cem:
  horizon           : 16
  init_cov          : 0.15
  cov_type          : 'full'
  beta              : 0.45
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.1
  num_cpu           : 10
  particles_per_cpu : 4
  base_action       : 'null'


dmd:
  horizon           : 16
  init_cov          : 0.45
  update_cov        : True
  cov_type          : 'full'
  beta              : 0.85
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 0.7
  lam               : 0.1
  num_cpu           : 10
  particles_per_cpu : 4
  sample_mode       : 'mean'
  base_action       : 'null'


pfmpc:
  horizon           : 16
  cov_shift         : 0.55
  cov_resample      : 1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  lam               : 0.2
  num_cpu           : 10
  particles_per_cpu : 4
  base_action       : 'null'


softq:
  horizon           : 32
  max_iters         : 10
  gamma             : 1.0
  init_cov          : 0.15 
  lam               : 0.1
  lr                : 0.01
  tol               : 0.0001
  num_samples       : 100
  base_action       : 'null'
