body_mass:
  cart: [0.3, 0.0]
  pole: [0.3, 0.0]
body_inertia:
  cart: [0.1, 0.1]
  pole: [0.1, 0.1]
dof_damping:
  slider: [0.1, 0.1]
  hinge: [0.1, 0.1]
dof_frictionloss:
  slider: [0.01, 0.01]
  hinge: [0.01, 0.01]
