env_name          : 'SimplePendulum-v0'
n_episodes        : 10
max_ep_length     : 200
seed              : 0
render            : True
exp_notes         : 'Swingup of a simple pendulum'

random_shooting:
  horizon           : 32
  init_cov          : 3.0
  filter_coeffs     : [0.6, 0.5, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 12
  particles_per_cpu : 3
  sample_mode       : 'mean'
  base_action       : 'null'

mppi:
  horizon           : 32
  init_cov          : 3.0
  filter_coeffs     : [0.6, 0.5, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.01
  alpha             : 0
  num_cpu           : 12
  particles_per_cpu : 3
  sample_mode       : 'mean'
  base_action       : 'null'

cem:
  horizon           : 32
  init_cov          : 3.0
  filter_coeffs     : [0.6, 0.5, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.2
  num_cpu           : 12
  particles_per_cpu : 3
  sample_mode       : 'mean'
  base_action       : 'null'

pfmpc:
  horizon           : 32
  cov_shift         : 0.55
  cov_resample      : 3.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  lam               : 0.2
  num_cpu           : 12
  particles_per_cpu : 3
  sample_mode       : 'mean'
  base_action       : 'null'




