env_name          : 'SimplePendulum-v0'
n_episodes        : 1
max_ep_length     : 200
seed              : 123
render            : True
exp_notes         : 'Swingup of a simple pendulum'


actor_params:
  actor_type   : 'linear_gaussian'
  min_log_std  : -5   
  init_log_std : 0.0

reinforce:
  horizon           : 32
  gamma             : 0.99
  n_iters           : 2
  lr                : 0.01
  num_cpu           : 10
  particles_per_cpu : 10

 