env_name          : 'pen-v0'
n_episodes        : 25
max_ep_length     : 100
seed              : 123
base_action       : 'null'
render            : False
job_mode          : 'tune'
exp_notes         : 'In-hand manipulation of a 6-DOF pen with a 24-DOF Shadow Hand (Adroit).'

random_shooting:
  horizon           : 32
  init_cov          : 0.7
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 10
  particles_per_cpu : 10

mppi:
  horizon           : 32
  init_cov          : 0.55
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.9
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : 10

cem:
  horizon           : [8, 16, 32, 64, 128]
  init_cov          : 0.25
  cov_type          : 'full'
  beta              : 0.9
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.05
  num_cpu           : 10
  particles_per_cpu : [2, 4, 6, 8, 10, 12]

dmd:
  horizon           : [8, 16, 32, 64, 128]
  init_cov          : 0.25
  update_cov        : True
  cov_type          : 'full'
  beta              : 0.6
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 0.7
  lam               : 0.2
  num_cpu           : 10
  particles_per_cpu : [2, 4, 6, 8, 10, 12]


pfmpc:
  horizon           : 32
  cov_shift         : 0.55
  cov_resample      : 1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  lam               : 0.5
  num_cpu           : 10
  particles_per_cpu : 10
