env_name          : 'mjrl_point_mass-v0'
n_episodes        : 5
max_ep_length     : 25
seed              : 123
base_action       : 'null'
render            : True
job_mode          : 'enum'
exp_notes         : 'Toy experiment with point mass'

random_shooting:
  horizon           : 5
  init_cov          : 1.0
  filter_coeffs     : [0.1, 0.0, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 8
  particles_per_cpu : 4

mppi:
  horizon           : 5
  init_cov          : 1.0
  filter_coeffs     : [0.1, 0.0, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.5
  alpha             : 1
  num_cpu           : 8
  particles_per_cpu : 4

cem:
  horizon           : 5
  init_cov          : 1.0
  cov_type          : 'full'
  beta              : 0.45
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.1
  num_cpu           : 8
  particles_per_cpu : 4

dmd:
  horizon           : 5
  init_cov          : 0.1
  update_cov        : True
  cov_type          : 'full'
  beta              : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 0.95
  lam               : 0.6
  num_cpu           : 8
  particles_per_cpu : 4

pfmpc:
  horizon           : 16
  cov_shift         : 0.15
  cov_resample      : 1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  lam               : 0.25
  num_cpu           : 8
  particles_per_cpu : 4



