env_name: 'point-v0'
n_episodes: 2
max_ep_length: 500
seed: 123
base_action: 'null'
render: True

mppi:
  horizon           : 16
  init_cov          : 1.0
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.2
  alpha             : 1
  num_cpu           : 8
  particles_per_cpu : 4
  base_action       : 'null'
  time_based_weights: False
  use_zero_control_seq: True

