env_name          : 'trajopt_reacher-v0'
n_episodes        : 10
max_ep_length     : 200
seed              : 0
n_iters           : 1
H                 : 32
particles_per_cpu : 3
num_cpu           : 12
filter_coeffs     : 
                    - 0.7 
                    - 0.1 
                    - 0.0
init_cov          : 3.0
gamma             : 1.0
step_size         : 0.55
lam               : 0.01
alpha             : 0
render            : False
exp_notes         : '7-DOF Sawyer arm reaching various spatial goals for the end effector'
