env_name          : 'sawyer_peg_insertion-v0'
n_episodes        : 25
max_ep_length     : 75
seed              : 123
base_action       : 'null'
render            : False
job_mode          : 'enum'
exp_notes         : '7-DOF Sawyer arm reaching various spatial goals for the end effector'


random_shooting:
  horizon           : [8, 16, 32, 64, 128]
  init_cov          : 0.1
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  num_cpu           : 10
  particles_per_cpu : [2, 4, 6, 8, 10, 12]

mppi:
  horizon           : [8, 16, 32, 64, 128]
  init_cov          : 0.1
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  lam               : 0.6
  alpha             : 1
  num_cpu           : 10
  particles_per_cpu : [2, 4, 6, 8, 10, 12]

cem:
  horizon           : [8, 16, 32, 64, 128]
  init_cov          : 0.1
  cov_type          : 'full'
  beta              : 0.45
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 1.0
  elite_frac        : 0.1
  num_cpu           : 10
  particles_per_cpu : [2, 4, 6, 8, 10, 12]

dmd:
  horizon           : [8, 16, 32, 64, 128]
  init_cov          : 0.1
  update_cov        : True
  cov_type          : 'full'
  beta              : 0.25
  filter_coeffs     : [0.25, 0.8, 0.0]
  gamma             : 1.0
  n_iters           : 1
  step_size         : 0.95
  lam               : 0.6
  num_cpu           : 10
  particles_per_cpu : [2, 4, 6, 8, 10, 12]



#N=64
# random_shooting:
#   horizon           : 16
#   init_cov          : 0.1
#   filter_coeffs     : [0.25, 0.8, 0.0]
#   gamma             : 1.0
#   n_iters           : 1
#   step_size         : 1.0
#   num_cpu           : 8
#   particles_per_cpu : 8

# mppi:
#   horizon           : 16
#   init_cov          : 0.1
#   filter_coeffs     : [0.25, 0.8, 0.0]
#   gamma             : 1.0
#   n_iters           : 1
#   step_size         : 1.0
#   lam               : 0.2
#   alpha             : 1
#   num_cpu           : 8
#   particles_per_cpu : 8

